// const String DEV_PROD = "dev";
const String DEV_PROD = "prod";
// const String MAIN_URL ="https://boknyyx648.execute-api.eu-central-1.amazonaws.com/"+DEV_PROD;
//  const String MAIN_URL ="http://apipy-stg.trackware.com";
// const String MAIN_URL ="http://apipy.trackware.com";//pord
const String MAIN_URL ="http://192.168.1.82:8000";
// const String SCHOOLS_LIST = "https://trackware-schools.s3.eu-central-1.amazonaws.com/tst.json";//dev
// const String SCHOOLS_LIST = "https://trackware-schools.s3.eu-central-1.amazonaws.com/qc1.json";//dev
// const String SCHOOLS_LIST = "https://trackware-schools.s3.eu-central-1.amazonaws.com/infos.json";//prod
// const String Logout = "/parents/logout/";
const String Login1 = "/unv/student_login_uni";
const String PostProfile = "/unv/profile";
const String GetRouts = "/unv/routs_uni_map";
// const String Feed_back = "/parents/feed-back/";
// const String Kids_history = "/parents/kids-history-new";
// const String Read_message = "/parents/read-message";
// const String Hide_message = "/parents/hide-message";
// const String Read_survey = "/parents/read-survey";
// const String Hide_survey = "/parents/hide-survey";
// // const String Settings = "/api/parents/settings";
// const String Settings = "/parents/settings";
// // const String Kids_List = "/api/parents/kids_list";
// const String Kids_List = "/parents/kids_list";
// const String Perent_Notification = "/notify";
// const String Get_Last_Location = "/rt/api/schools/bus_location?";
// const String Pre_Arrive = "/parents/pre-arrive";
// const String Get_Clinic="/api/get_clinic/";
// const String Get_Ass="/api/get_assignment/";
// const String Get_Exam="/api/get_exam/";
// const String Get_Badges="/api/get_badges/";
// const String Get_Calendar="/api/get_calendar/";
// const String Get_All_Weekly="/api/get_all_weekly_plans/";
// const String Get_All_Worksheets="/api/get_worksheets/";
// const String Get_All_Events="/api/get_events/";
// const String Get_All_Product="/api/get_product";
// const String Get_All_Allergies="/api/get_Allergies";
// const String Get_canteen="/api/canteen";
// const String Post_Spending="/api/post_spending";
// const String Get_Weekly="/api/get_weekly_plan_lines/";
// const String Get_Absence="/api/get_attendance/";
// const String Get_Library="/api/get_library/";
// const String Get_WorkSheet="/api/get_worksheet_view_data/";
// const String Get_Event="/api/get_event_form_view_data/";
// const String Post_Absence="/parents/post-attendance";
// const String Post_worksheet="/parents/post-worksheet";
// const String Post_Event="/parents/post-Event";
// const String Post_Library="/parents/post_library";
// const String Cancel_Event="/parents/cancel-event";
// const String Get_Time_Table="/api/get_time_table/";
// const String Get_Category="/api/get_category";
// const String Post_banned="/api/post_banned";
// const String Get_Item="/api/get_Item";
// const String Post_banned_item="/api/post_banned_item";
// const String Post_sec_item="/api/post_sec_item";
// const String Get_banned_student="/api/get_banned_student";
// const String Delete_banned="/api/delete_banned";
// const String Delete_food="/api/delete_food";
// const String Get_food_student="/api/get_food_s";
//
//
//
//
